<!-- START: Cookie-bar CSS -->
<style type="text/css">#ww-cookie-information,#ww-cookie-information *{box-sizing:border-box}#ww-cookie-information{padding:5px 10px;position:fixed;bottom:-100%;left:0;z-index:999999;height:auto;width:100%;background-color:#000;background-color:rgba(0,0,0,.8);-webkit-transition:bottom 1s;transition:bottom 1s;color:#fff;font-family:sans-serif;font-weight:300}#ww-cookie-information.active{bottom:0}#ww-cookie-information.inactive{display:none}#ww-cookie-information .ww-wrap{display:block;margin:0 auto;max-width:1140px;width:100%;font-size:14px}#ww-cookie-information .ww-wrap button,#ww-cookie-information .ww-wrap span{display:inline-block}#ww-cookie-information .ww-wrap>span{margin-top:5px}#ww-cookie-information .ww-wrap span{width:88%}#ww-cookie-information .ww-wrap span a{color:inherit;text-decoration:underline}#ww-cookie-information .ww-wrap span .domain{display:inline;width:auto}#ww-cookie-information .ww-wrap button{padding:4px 10px;vertical-align:top;background-color:#C79C60;border:none;border-radius:2px;cursor:pointer;font:inherit;color:#fff;font-weight:300}#ww-cookie-information .ww-wrap button:hover,#ww-cookie-information .ww-wrap span a:hover{color:#eee}@media (max-width:1050px){#ww-cookie-information .ww-wrap{text-align:center}#ww-cookie-information .ww-wrap button{display:block;margin:10px auto 0}}</style>
<!-- END: Cookie-bar CSS -->

<!-- START: Cookie-bar HTML -->
<div id="ww-cookie-information" class="inactive"><div class="ww-wrap"><span><span class="domain">Den här webbplatsen</span> använder <a href="/cookies">cookies</a> för att förbättra användarupplevelsen. Genom att fortsätta använda sidan godkänner du detta.</span> <button id="ww-cookie-consent" type="button">Jag förstår!</button></div></div>
<!-- END: Cookie-bar HTML -->

<!-- START: Cookie-bar JS -->
<script type="text/javascript">function setCookie(){var e=new Date;e.setFullYear(e.getFullYear()+1),document.cookie=cookieName+"=true; expires="+e.toUTCString()+"; path=/"}var cookieName="ww_cookie_consent";if(document.cookie.indexOf(cookieName)<0){var cookieInfo=document.getElementById("ww-cookie-information"),cookieConsent=document.getElementById("ww-cookie-consent"),showDelay=100,domain="";domain&&(document.getElementById("ww-cookie-information").getElementsByClassName("domain")[0].innerHTML=domain),cookieInfo.className="",setTimeout(function(){cookieInfo.className="active"},showDelay),cookieConsent.addEventListener("click",function(){setCookie(),cookieInfo.className="",setTimeout(function(){cookieInfo.className="inactive"},5e3)})}else document.cookie.indexOf(cookieName)>=0&&setCookie();</script>
<!-- END: Cookie-bar JS -->
